services:

  mysql:
    image: mysql:8.0
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: Sonu@123
      MYSQL_DATABASE: timesheet_db

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  timesheet-app:
    image: timesheet-app:latest
    container_name: timesheet-app

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8081:8080"

volumes:
  mysql-data: